2023-09-07 12:22:02,114 INFO    MainThread:22812 [wandb_setup.py:_flush():76] Current SDK version is 0.15.9
2023-09-07 12:22:02,115 INFO    MainThread:22812 [wandb_setup.py:_flush():76] Configure stats pid to 22812
2023-09-07 12:22:02,115 INFO    MainThread:22812 [wandb_setup.py:_flush():76] Loading settings from C:\Users\User\.config\wandb\settings
2023-09-07 12:22:02,115 INFO    MainThread:22812 [wandb_setup.py:_flush():76] Loading settings from C:\Users\User\Desktop\MyProjects\waterbirds_training\wandb\settings
2023-09-07 12:22:02,115 INFO    MainThread:22812 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-09-07 12:22:02,115 INFO    MainThread:22812 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'main.py', 'program': 'C:\\Users\\User\\Desktop\\MyProjects\\waterbirds_training\\main.py'}
2023-09-07 12:22:02,115 INFO    MainThread:22812 [wandb_init.py:_log_setup():524] Logging user logs to C:\Users\User\Desktop\MyProjects\waterbirds_training\wandb\run-20230907_122202-cakqv07k\logs\debug.log
2023-09-07 12:22:02,115 INFO    MainThread:22812 [wandb_init.py:_log_setup():525] Logging internal logs to C:\Users\User\Desktop\MyProjects\waterbirds_training\wandb\run-20230907_122202-cakqv07k\logs\debug-internal.log
2023-09-07 12:22:02,115 INFO    MainThread:22812 [wandb_init.py:init():564] calling init triggers
2023-09-07 12:22:02,115 INFO    MainThread:22812 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {'_metadata': ContainerMetadata(ref_type=typing.Any, object_type=<class 'dict'>, optional=True, key='dataset', flags={}, flags_root=False, resolver_cache=defaultdict(<class 'dict'>, {}), key_type=typing.Any, element_type=typing.Any), '_parent': {'algorithm': {'name': 'jtt', 'params': {'lambda_up': 100, 'num_epochs_for_final_model': 300}, 'data_format': 'vector'}, 'model': {'name': 'linear_classifier', 'linear_config': {'_target_': 'models.LinearClassifier'}, 'params': {'num_classes': 2, 'num_epochs': 60}, 'data_format': 'vector'}, 'dataset': {'name': 'resnet50_representation', '_target_': 'datamodule.representation_data.DataModule', 'in_features': 2048, 'batch_size': 64, 'train_path': '${oc.env:DATA_ROOT}/resnet50/train.npz', 'test_path': '${oc.env:DATA_ROOT}/resnet50/test.npz', 'val_path': '${oc.env:DATA_ROOT}/resnet50/val.npz', 'data_format': 'vector'}, 'optimizer': {'name': 'adam', 'optim': {'_target_': 'torch.optim.Adam', 'lr': 0.001, 'weight_decay': 1e-05}}, 'loss': {'name': 'cross_entropy', 'loss_function': {'_target_': 'torch.nn.CrossEntropyLoss'}}}, '_flags_cache': {'struct': True}, '_content': {'name': 'resnet50_representation', '_target_': 'datamodule.representation_data.DataModule', 'in_features': 2048, 'batch_size': 64, 'train_path': '${oc.env:DATA_ROOT}/resnet50/train.npz', 'test_path': '${oc.env:DATA_ROOT}/resnet50/test.npz', 'val_path': '${oc.env:DATA_ROOT}/resnet50/val.npz', 'data_format': 'vector'}}
2023-09-07 12:22:02,115 INFO    MainThread:22812 [wandb_init.py:init():613] starting backend
2023-09-07 12:22:02,115 INFO    MainThread:22812 [wandb_init.py:init():617] setting up manager
2023-09-07 12:22:02,115 INFO    MainThread:22812 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-09-07 12:22:02,115 INFO    MainThread:22812 [wandb_init.py:init():623] backend started and connected
2023-09-07 12:22:02,476 ERROR   MainThread:22812 [wandb_init.py:init():1192] error
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 1164, in init
    run = wi.init()
          ^^^^^^^^^
  File "C:\Users\User\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_init.py", line 628, in init
    run = Run(
          ^^^^
  File "C:\Users\User\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 537, in __init__
    self._init(
  File "C:\Users\User\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_run.py", line 653, in _init
    self._config._update(config, ignore_locked=True)
  File "C:\Users\User\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_config.py", line 177, in _update
    sanitized = self._sanitize_dict(
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_config.py", line 237, in _sanitize_dict
    k, v = self._sanitize(k, v, allow_val_change)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Roaming\Python\Python311\site-packages\wandb\sdk\wandb_config.py", line 255, in _sanitize
    val = json_friendly_val(val)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Roaming\Python\Python311\site-packages\wandb\util.py", line 663, in json_friendly_val
    converted = asdict(val)
                ^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\dataclasses.py", line 1284, in asdict
    return _asdict_inner(obj, dict_factory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\dataclasses.py", line 1291, in _asdict_inner
    value = _asdict_inner(getattr(obj, f.name), dict_factory)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\dataclasses.py", line 1321, in _asdict_inner
    return type(obj)((_asdict_inner(k, dict_factory),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: first argument must be callable or None
